# common config
rdebug-dir: /tmp/midi/

# config for koala
koala:
    inbound-port: 5514
    sub-port: 5515
    outbound-port: 5516
    bypass-ports:
        - 9666
    replay-match-threshold: 0.75
    inbound-read-timeout: 86400s
    gc-global-status-timeout: 86400s
    inbound-protocol: HTTP # HTTP or FastCGI, default is HTTP

redirect-dir:
    # /path/to/old/dir : /path/to/new/dir
mock-files:
    # mock filename content
    # /path/to/need/mock/filename: base64_encode(your-mock-content)

record-host:

php:
    deploy-path:
    koala-php-ini:
        memory_limit: 1G
        error_log: /tmp/midi/logs/php-error.log
    pre-inject-file:
    session-resolver: Midi\Resolver\ElasticResolver
    differ: Midi\Differ\Differ
    preload-plugins:
        - Midi\ElasticPlugin
    plugins:
#        - DiPlugin\Plugin
    custom-commands:
#        - DiPlugin\Command\DoctorCommand
#        - DiPlugin\Command\InitCommand
#        - DiPlugin\Command\SearchCommand
    elastic-search-url:
    autoloader:
        psr-0:
        psr-4:
        classmap:
        #    - MyNamespace\MyClass: '/path/to/MyClass.php'

    # For DiPlugin
    module-name:
    enable-uploader: 1
    uploader-url:
    recommend-dsl-url:
    enable-disf: false
    module-disf-name:
